Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false
